// Code generated by codegen. DO NOT EDIT!!!

package runtime

import (
	"github.com/wujie1993/waves/pkg/e"
	"github.com/wujie1993/waves/pkg/orm/core"
)

var helper Helper

func init() {
	helper = Helper{}
}

// Helper 对runtime版本所有实体对象的操作封装
type Helper struct {
}

func GetHelper() Helper {
	return helper
}

// New 创建一个新的实体对象
func New(kind string) (core.ApiObject, error) {
	switch kind {

	case core.KindAppInstance:
		return NewAppInstance(), nil

	case core.KindJob:
		return NewJob(), nil

	default:
		return nil, e.Errorf("unknown kind of %s within runtime", kind)
	}
}
