FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y openssh-server
RUN ssh-keygen -A
RUN echo 'waves123\nwaves123' | passwd root
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN mkdir /run/sshd
CMD SSH_USE_STRONG_RNG=0 /usr/sbin/sshd -D
