// Code generated by codegen. DO NOT EDIT!!!

package v1

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
)

func (obj App) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj AppInstance) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Audit) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj ConfigMap) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Event) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj GPU) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Host) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Job) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj K8sConfig) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Namespace) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Pkg) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Project) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (obj Revision) Sha256() string {
	data, _ := json.Marshal(obj)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}
