// Code generated by codegen. DO NOT EDIT!!!

package v1

import (
	"encoding/json"

	"github.com/ghodss/yaml"
)

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj App) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj App) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *App) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj App) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *App) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj AppInstance) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj AppInstance) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *AppInstance) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj AppInstance) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *AppInstance) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Audit) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Audit) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Audit) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Audit) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Audit) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj ConfigMap) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj ConfigMap) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *ConfigMap) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj ConfigMap) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *ConfigMap) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Event) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Event) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Event) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Event) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Event) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj GPU) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj GPU) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *GPU) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj GPU) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *GPU) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Host) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Host) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Host) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Host) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Host) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Job) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Job) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Job) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Job) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Job) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj K8sConfig) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj K8sConfig) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *K8sConfig) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj K8sConfig) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *K8sConfig) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Namespace) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Namespace) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Namespace) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Namespace) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Namespace) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Pkg) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Pkg) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Pkg) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Pkg) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Pkg) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Project) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Project) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Project) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Project) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Project) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}

// ToJSON is auto generated by codegen, marshal to json bytes
func (obj Revision) ToJSON() ([]byte, error) {
	return json.Marshal(obj)
}

// ToJSONPretty is auto generated by codegen, marshal to json bytes with pretty format
func (obj Revision) ToJSONPretty() ([]byte, error) {
	return json.MarshalIndent(obj, "", "\t")
}

// FromJSON is auto generated by codegen, unmarshal from json bytes
func (obj *Revision) FromJSON(data []byte) error {
	return json.Unmarshal(data, obj)
}

// ToYAML is auto generated by codegen, marshal to yaml bytes
func (obj Revision) ToYAML() ([]byte, error) {
	return yaml.Marshal(obj)
}

// FromYAML is auto generated by codegen, unmarshal from yaml bytes
func (obj *Revision) FromYAML(data []byte) error {
	return yaml.Unmarshal(data, obj)
}
