// Code generated by codegen. DO NOT EDIT!!!

package v1

import (
	"github.com/wujie1993/waves/pkg/orm/core"
)

// DeepCopyInto is auto generated by codegen, copy public fields into the *App
func (src App) DeepCopyInto(dst *App) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *App
func (src App) DeepCopy() *App {
	dst := new(App)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src App) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *AppInstance
func (src AppInstance) DeepCopyInto(dst *AppInstance) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *AppInstance
func (src AppInstance) DeepCopy() *AppInstance {
	dst := new(AppInstance)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src AppInstance) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Audit
func (src Audit) DeepCopyInto(dst *Audit) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Audit
func (src Audit) DeepCopy() *Audit {
	dst := new(Audit)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Audit) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *ConfigMap
func (src ConfigMap) DeepCopyInto(dst *ConfigMap) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *ConfigMap
func (src ConfigMap) DeepCopy() *ConfigMap {
	dst := new(ConfigMap)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src ConfigMap) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Event
func (src Event) DeepCopyInto(dst *Event) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Event
func (src Event) DeepCopy() *Event {
	dst := new(Event)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Event) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *GPU
func (src GPU) DeepCopyInto(dst *GPU) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *GPU
func (src GPU) DeepCopy() *GPU {
	dst := new(GPU)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src GPU) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Host
func (src Host) DeepCopyInto(dst *Host) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Host
func (src Host) DeepCopy() *Host {
	dst := new(Host)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Host) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Job
func (src Job) DeepCopyInto(dst *Job) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Job
func (src Job) DeepCopy() *Job {
	dst := new(Job)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Job) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *K8sConfig
func (src K8sConfig) DeepCopyInto(dst *K8sConfig) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *K8sConfig
func (src K8sConfig) DeepCopy() *K8sConfig {
	dst := new(K8sConfig)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src K8sConfig) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Namespace
func (src Namespace) DeepCopyInto(dst *Namespace) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Namespace
func (src Namespace) DeepCopy() *Namespace {
	dst := new(Namespace)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Namespace) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Pkg
func (src Pkg) DeepCopyInto(dst *Pkg) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Pkg
func (src Pkg) DeepCopy() *Pkg {
	dst := new(Pkg)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Pkg) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Project
func (src Project) DeepCopyInto(dst *Project) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Project
func (src Project) DeepCopy() *Project {
	dst := new(Project)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Project) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}

// DeepCopyInto is auto generated by codegen, copy public fields into the *Revision
func (src Revision) DeepCopyInto(dst *Revision) error {
	return core.DeepCopy(src, dst)
}

// DeepCopy is auto generated by codegen, create and copy public fields into the new *Revision
func (src Revision) DeepCopy() *Revision {
	dst := new(Revision)
	src.DeepCopyInto(dst)
	return dst
}

// DeepCopyApiObject is auto generated by codegen, deep copy and return as ApiObject
func (src Revision) DeepCopyApiObject() core.ApiObject {
	return src.DeepCopy()
}
