// Code generated by codegen. DO NOT EDIT!!!

package v2

import (
	"github.com/wujie1993/waves/pkg/e"
	"github.com/wujie1993/waves/pkg/orm/core"
)

var helper Helper

func init() {
	helper = Helper{
		AppInstance: NewAppInstanceRegistry(),
		Host:        NewHostRegistry(),
		Job:         NewJobRegistry(),
	}
}

// Helper 对v2版本所有实体对象的操作封装
type Helper struct {
	AppInstance *AppInstanceRegistry
	Host        *HostRegistry
	Job         *JobRegistry
}

func GetHelper() Helper {
	return helper
}

// New 创建一个新的实体对象
func New(kind string) (core.ApiObject, error) {
	switch kind {
	case core.KindAppInstance:
		return NewAppInstance(), nil
	case core.KindHost:
		return NewHost(), nil
	case core.KindJob:
		return NewJob(), nil
	default:
		return nil, e.Errorf("unknown kind of %s within v2", kind)
	}
}
