name: ci

on:
  push:
    branches: [ main,ci ]
  pull_request:
    branches: [ main,ci ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
   
    - name: Show go envs
      run: go env
   
    - name: Cache go pkgs
      uses: actions/cache@v2
      env:
        cache-name: cache-go-pkgs
        GOPATH: /home/runner/go
      with:
        path: ${{ env.GOPATH }}/pkg
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./go.sum') }}

    - name: Install swag
      run: git clone -b v1.6.7 https://github.com/swaggo/swag.git $GOPATH/src/github.com/swaggo/swag && go install github.com/swaggo/swag/cmd/swag
      env:
        GOPATH: /home/runner/go

    - name: Get packages
      run: go get -v ./...

    - name: Build
      run: make
    
    - name: Test
      run: make test

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      run: make image

