name: waves

on:
  push:
    branches: [ main,ci ]
  pull_request:
    branches: [ main,ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
   
    - name: Show go envs
      run: go env
   
    - name: Cache go pkgs
      uses: actions/cache@v2
      env:
        cache-name: cache-go-pkgs
        GOPATH: /home/runner/go
      with:
        path: ${{ env.GOPATH }}/pkg
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./go.sum') }}

    - name: Install swag
      run: git clone -b v1.6.7 https://github.com/swaggo/swag.git $GOPATH/src/github.com/swaggo/swag && go install github.com/swaggo/swag/cmd/swag
      env:
        GOPATH: /home/runner/go

    - name: Get packages
      run: go get -v ./...

    - name: Build
      run: make

  test:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.3.19
        ports:
        - 2379:2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379 
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Cache go pkgs
      uses: actions/cache@v2
      env:
        cache-name: cache-go-pkgs
        GOPATH: /home/runner/go
      with:
        path: ${{ env.GOPATH }}/pkg
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./go.sum') }}
    
    - name: Get packages
      run: go get -v ./...

    - name: Test
      run: make test
