name: Go

on:
  push:
    branches: [ main,ci ]
  pull_request:
    branches: [ main,ci ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
   
    - name: Show go envs
      run: go env
   
    - name: Install swag
      run: git clone -b v1.6.7 https://github.com/swaggo/swag.git $GOPATH/src/github.com/swaggo/swag && go install github.com/swaggo/swag/cmd/swag
   
    - name: Get packages
      run: go get -v ./...

    - name: Build
      run: make

    #- name: Test
    #  run: go test -v ./...
